site_name: X86_64_EMU_SOFT Documentation
nav:
  - Home: index.md
  - Content: Content.md
  - About: about.md
  - 1 Emulator:
    - 1.2 Comand Line Arguments:
       - 1.2.1 Basic Syntax: Emulator/Comand_Line_Arguments/Basic_Syntax.md
       - 1.2.2 Devices: Emulator/Comand_Line_Arguments/Devices.md
  - 2 API:
    - 2.0 API: API/API.md
    - 2.1 X86_64_EMU_SOFT: 
      -  X86_64_EMU_SOFT namespace: API/X86_64_EMU_SOFT/X86_64_EMU_SOFT.md
      - HELPERS:
        - HELPERS namespace: API/X86_64_EMU_SOFT/HELPERS/HELPERS.md
        - CmdParse: API/X86_64_EMU_SOFT/HELPERS/CMD_PARSE.md
        - Diff: API/X86_64_EMU_SOFT/HELPERS/DIFF.md
        - GetBit: API/X86_64_EMU_SOFT/HELPERS/GET_BIT.md
        - Set Bit: API/X86_64_EMU_SOFT/HELPERS/SET_BIT.md
      - SYSTEM:
        - CPU: 
          - CPU: API/X86_64_EMU_SOFT/SYSTEM/CPU/index.md 
          - GENERAL_PROTECTION_FAULT: API/X86_64_EMU_SOFT/SYSTEM/CPU/EXCEPTIONS/GENERAL_PROTECTION_FAULT.md
          - EXCEPTIONS:
            - EXCEPTIONS: API/X86_64_EMU_SOFT/SYSTEM/CPU/EXCEPTIONS/index.md
        - IO_DEVICES:
          - Device Base: API/X86_64_EMU_SOFT/SYSTEM/IO_DEVICES/DeviceBase.md
        - MEMORY:
          - MEMORY namespace: API/X86_64_EMU_SOFT/SYSTEM/MEMORY/MEMORY_NAMESPACE.md
          - Memory Bus: API/X86_64_EMU_SOFT/SYSTEM/MEMORY/MEMORY.md
    - 2.2 Device Handlers: API/DeviceHandlers/DeviceHandlers.md


theme: readthedocs


markdown_extensions:
  - toc:
      permalink: "#"
  - def_list:
