#pragma once
#include "SYSTEM/CPU/REGISTERS/GPR.h"
#include "SYSTEM/CPU/REGISTERS/CONTROLL_REGISTERS/CR0.h"
#include "SYSTEM/CPU/REGISTERS/MSR/EFER.h"
#include "SYSTEM/CPU/REGISTERS/RIP.h"
namespace X86_64_EMU_SOFT::SYSTEM::CPU
{
		
		
			class VirtualCore
			{
				REGISTERS::GPR RAX;
				REGISTERS::GPR RBX;
				REGISTERS::GPR RCX;
				REGISTERS::GPR RDX;
				REGISTERS::GPR RSI;
				REGISTERS::GPR RDI;
				REGISTERS::GPR RSP;
				REGISTERS::GPR RBP;
				REGISTERS::GPR R8;
				REGISTERS::GPR R9;
				REGISTERS::GPR R10;
				REGISTERS::GPR R11;
				REGISTERS::GPR R12;
				REGISTERS::GPR R13;
				REGISTERS::GPR R14;
				REGISTERS::GPR R15;

				REGISTERS::RIP RIP;
			};
	
}